### ISSUE TITLE
[Feat] additional service of chat

### ISSUE THREAD

**Issue by H4nnhoi** [project-web-chatty/chatty-server#22]
# TODO
- [ ] count unread message count
- [ ] get message by pagination
- [ ] setting start page of message
