### ISSUE TITLE
[Refactor] relations of chatting service

### ISSUE THREAD

**Issue by H4nnhoi** [project-web-chatty/chatty-server#28]
# TODO
- [ ] get unread message when getting channel info
- [ ] divide MessageDto(response, request)
- [ ] getting message dto from front
